[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "ed0fa87385f36e9eeef69d0acb70bd5cf88cee67"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "29c5a608861cc9c06d3f86852a7d7b1a868de2d7ab90d4ff625aeebfb9383390"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c3865d8b1827775f9569e7bc11f49f7d6989ec48"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bad9a353330d9f409fe9db790da5701074112f804073506bb2808dd97b940b3c"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "699e2ff34411eeecec59dc75b482ad8f9c25ca16"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "7f455c2b498a6197db7f00d636899ed0fb20ce152f1b1573a3ee524ee98b1b80"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab28e30c68fb3ee9fbf9ebbe9ab2c44548c8aa5f"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d86de4cd9e8264ff8dff1b2ec52b8fd2dbb9a01acb6c23ad73e38695d2de98e6"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "c9e1eca99029470a8b6e89094930d9a0a5550c17"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "1a357b1e44f7ec7c2da62461a4180d8d8b599dd06045e7e2b83cd7f93972d6d7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "207eaf0e37af6a303baf5b38776a53a2d225e216"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "216a1c6d178e0494ac488f3310e600ef17c62ce38d43e9b14557d1f16f3637f7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "7f59d1ceccd777bdc19709ab9918a2e1b3ce698c"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "58344f7047aceefa44e9aef552b9b84ae3d16fded31a5c6ba9b63abc2c269f43"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "cce6f7e2b5bb575a13eac72dc0d0db828677cf2b"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "bc5d90c9286f7c44dac7d44fabe815ec87e661a4b1b3e5b51c4a71890680b2d1"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-pc-windows-gnullvm.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "002276e90ea55e17700d23dc922a10230789d731"
lazy = true
os = "netbsd"

    [[RustToolChain.download]]
    sha256 = "4666e7d6621a2d90220fca136e9f6e6b437e5159ec7ce008fd95a9f2a0aff909"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-netbsd.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "0576770f76e2aabd8bee98479071e72afc385365"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "cbd14c36f039f6f11f38148a6295d8234d18ddf20bea53031c86f119423a8b26"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-aarch64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "b584d3deca20278ac027b90ef8123029be3662f9"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "5f4c84d2bcce7983468642855a45fc4978fba1324cfdd1ea0b182face3ab4ffa"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-x86_64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "4407e3a41fdd3b0598d6c9f2376e44ba55f2aac5"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "914c2702deada0b9cf1d64bb3495d76e55cb3eba07d508472dde8b55a93e3759"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "8c034c216dbbf43e1b759696aa20556a00e928fe"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "b4cdbc7cc6b0ee0a2666b1872769fdb2ad8393b28b63952f6493b4b400e4832b"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "8ddf31999c6738c5bbc68dc5f3705beb18d045c5"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "2f2496c70bd336a66a4c8baf2d303ba161f3552f192444c3639ba903c7c1e2c5"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c4a6ffeedfe54cdcf15a2274fb8056efa5b509a"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "ba62fe07ad85b507907705a14adc1e8bc258de5f6177ba41d77bbff9f469a4ce"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-arm-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7220f05e8164be2cd9e522f1e48a439950d48f82"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e89c5e33aaddc6ef56857000c9117875c2997e9a1a500bd7b16277c9874b002f"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "3df0b38508b2a48247104cd94e9d7bc69a427e2c"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "ff524eef5a59d801df09ccad5cdaf9ea1f0a07d75cbed2a7e9f013a9eb76a3c1"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "9913c52722c84ebadd72b3ca446baa5831f8aeb7"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "59bec35d8febb2ab918fa41cffbaa5b07146a63bdc33f029ff756d70a3151ece"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "2b2527d440b070ae291890f4305312081bd97e08"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "40dbea28193cf2b488cf3e4a89274ccfb60efa50883f19917a382f84fd05bdc4"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-x86_64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "531874c9a255e17ffac3b568a3f033529dc52bf0"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "c5f45b5c6eb7f8fdb277c54c08402b7c931516740fbd4eccc26ba148f7cd5d57"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-aarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "839a270c8915818e97074c1dbca16b493a46009f"
lazy = true
os = "freebsd"

    [[RustToolChain.download]]
    sha256 = "77866a4c449bcccb40e9d6712bf3eb899d29018ed8e841fd9d8d59370751f152"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-x86_64-unknown-freebsd.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "c9e9579177ff7c7f46c5a4a6c3bf3b68eb20e6de"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "a85387f0c2b421c69cf7efe874fa051ab0cc511904ceb3645ab359256a214e1f"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-i686-pc-windows-msvc.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "e264336bffecf74b006798a8a36bb4bf98c996d8"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "efbb66ddc8ca271424e5bf4de9b5c552c2f6cc68e36309b2c7bbe683c72d0334"
    url = "https://static.rust-lang.org/dist/rust-1.97.1-x86_64-pc-windows-msvc.tar.gz"
