[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "ed0fa87385f36e9eeef69d0acb70bd5cf88cee67"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "29c5a608861cc9c06d3f86852a7d7b1a868de2d7ab90d4ff625aeebfb9383390"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c3865d8b1827775f9569e7bc11f49f7d6989ec48"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bad9a353330d9f409fe9db790da5701074112f804073506bb2808dd97b940b3c"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "699e2ff34411eeecec59dc75b482ad8f9c25ca16"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "7f455c2b498a6197db7f00d636899ed0fb20ce152f1b1573a3ee524ee98b1b80"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab28e30c68fb3ee9fbf9ebbe9ab2c44548c8aa5f"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d86de4cd9e8264ff8dff1b2ec52b8fd2dbb9a01acb6c23ad73e38695d2de98e6"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "c9e1eca99029470a8b6e89094930d9a0a5550c17"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "1a357b1e44f7ec7c2da62461a4180d8d8b599dd06045e7e2b83cd7f93972d6d7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "207eaf0e37af6a303baf5b38776a53a2d225e216"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "216a1c6d178e0494ac488f3310e600ef17c62ce38d43e9b14557d1f16f3637f7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "7f59d1ceccd777bdc19709ab9918a2e1b3ce698c"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "58344f7047aceefa44e9aef552b9b84ae3d16fded31a5c6ba9b63abc2c269f43"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "cce6f7e2b5bb575a13eac72dc0d0db828677cf2b"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "bc5d90c9286f7c44dac7d44fabe815ec87e661a4b1b3e5b51c4a71890680b2d1"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-pc-windows-gnullvm.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "002276e90ea55e17700d23dc922a10230789d731"
lazy = true
os = "netbsd"

    [[RustToolChain.download]]
    sha256 = "4666e7d6621a2d90220fca136e9f6e6b437e5159ec7ce008fd95a9f2a0aff909"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-netbsd.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "3d339b6b9503cd555810908f3e12076e2becdfb9"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "cfc171d8120d401b10a1028c52646dd8e00e3e66852f949061ce087845f55afd"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-aarch64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "58453330e7dd023ace351a0fa4b7c8a484c24aa2"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "443a1165abbac41c9143b83ff837c0fb1d8c03d2f8fb1da27427bc9fc646aad3"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-x86_64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "1f839332bd36633cf6c994cf7564f408c0a08da1"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "22b82030ccbcb5c77f8740b06cb03a880ca9779e1b1ed9674eabb7b99eae55fc"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "7c7c6247fafc16852a7b63f6c7d95added4a3751"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "24ba1338a2d35c5a3247936546429e163fa674d726102af18bdf624582c57aea"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "72dbad58d52dcf79c736836122837ccc4b33fe29"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "f00ba576645cef658e1deed96fab8f707958e9d58808b16343448b5d1c4f7407"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b0c0c22fd23f62e23c587a03044716349a626579"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "c00bcf4ffe13e48f9fb89e5d643a58af1231baad6d189d1df5ca7b8d2ac71724"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-arm-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b68a5192d12a5545a6432e8fcd2126754bd646f5"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "50fcf1a6832d0709edec54b022453902ff88cfe4d0532826b42a51913b1462df"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "b0451739a9b30bb77164e25e61a6c64ef84103d4"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8fe46e66f8e28d6ba6d40dcb127a0bd0454b7a1fb6a6bf43b97f55cb64e18897"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "7a7f0068ed8f7cba2a77cc70b22c5171e3270976"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "df44f22fa550f0df5cd32230bd0712e7ce4a9ac9d77f02a33ac105317e0689c4"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "77a6c230f98f1d6f7249047c70c4d73384f86a15"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "4178195a7f39f2eeec01cc90d579707787a73c0f42d2bf943f78b8dbbac69c04"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-x86_64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "da24fdaf7da11e41a59446adcd65994f65a60fbb"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d134f371064241e21ad9dba15887b9ba805410948e05b93284d05a68b943950d"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-aarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "ae13ae6c3bd174a165dd405542049e46c2b9bdd7"
lazy = true
os = "freebsd"

    [[RustToolChain.download]]
    sha256 = "a89cdfd2c7099a5d25c2d398b00fe8cbf641b156b5af75ea572db3f0142b27dd"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-x86_64-unknown-freebsd.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "730370c690891ed28d97b7cfa7dcb5f713abcd39"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "0270ee093aa85c2c40eb154ad14f08f59ce9809d6f080582ad3e7c1f861d738f"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-i686-pc-windows-msvc.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "4486038d03577c6f59923b26c52d0a4d8b4e1328"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "b968b7969fa4f4e061d2246de655aa0b310c4f31faceb91f1be7baa12ab6c333"
    url = "https://static.rust-lang.org/dist/rust-1.98.1-x86_64-pc-windows-msvc.tar.gz"
