[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "ed0fa87385f36e9eeef69d0acb70bd5cf88cee67"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "29c5a608861cc9c06d3f86852a7d7b1a868de2d7ab90d4ff625aeebfb9383390"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "c3865d8b1827775f9569e7bc11f49f7d6989ec48"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "bad9a353330d9f409fe9db790da5701074112f804073506bb2808dd97b940b3c"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "699e2ff34411eeecec59dc75b482ad8f9c25ca16"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "7f455c2b498a6197db7f00d636899ed0fb20ce152f1b1573a3ee524ee98b1b80"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab28e30c68fb3ee9fbf9ebbe9ab2c44548c8aa5f"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "d86de4cd9e8264ff8dff1b2ec52b8fd2dbb9a01acb6c23ad73e38695d2de98e6"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "c9e1eca99029470a8b6e89094930d9a0a5550c17"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "1a357b1e44f7ec7c2da62461a4180d8d8b599dd06045e7e2b83cd7f93972d6d7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "207eaf0e37af6a303baf5b38776a53a2d225e216"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "216a1c6d178e0494ac488f3310e600ef17c62ce38d43e9b14557d1f16f3637f7"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "gnu"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "7f59d1ceccd777bdc19709ab9918a2e1b3ce698c"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "58344f7047aceefa44e9aef552b9b84ae3d16fded31a5c6ba9b63abc2c269f43"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "cce6f7e2b5bb575a13eac72dc0d0db828677cf2b"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "bc5d90c9286f7c44dac7d44fabe815ec87e661a4b1b3e5b51c4a71890680b2d1"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-aarch64-pc-windows-gnullvm.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "002276e90ea55e17700d23dc922a10230789d731"
lazy = true
os = "netbsd"

    [[RustToolChain.download]]
    sha256 = "4666e7d6621a2d90220fca136e9f6e6b437e5159ec7ce008fd95a9f2a0aff909"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-x86_64-unknown-netbsd.tar.gz"
[[RustToolChain]]
arch = "s390x"
git-tree-sha1 = "323be219d0335225a4634db12510a7ac856d8926"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "e2cda4e86f68e3d4ca9df4f9d80d53fc34a555a96012fceefa4190a388e987d4"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-s390x-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "loongarch64"
git-tree-sha1 = "0515d200cbf18fc57740d81ad0f08916fe1e982b"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "8121c8d7d9152a835c84bf6b586c107ae582ed051780d37cb1e6f4f9bdad23aa"
    url = "https://static.rust-lang.org/dist/rust-1.91.0-loongarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "482cd903762f4658d9db06e7c79b5cad0e1bcc40"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "026ec75bec81fb8c10b11df98f1336ee39f4bc11e04d6745dffe9fca81e5c0b5"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-aarch64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "356dd74e6fc594684dcce5fac25f555da67bc00f"
lazy = true
os = "macos"

    [[RustToolChain.download]]
    sha256 = "66f4e2e17275753deaba8437380de21072b56b5a083cf954bacb6376df0834fc"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-x86_64-apple-darwin.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "c63c8f5e3aed0b4c868ca56a225439ba49cd88fa"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "2706508ca1bc0e2a1205b761d6044d0185bbe322d437225a6c6b74fa917616ab"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-i686-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "f13dc10eeecdd7203a5be9a624aee9b0d703fdb8"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "aa30409afa67bd1ada244cefd82c7980e6a65bc113bb978e934b2413c75e3900"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-x86_64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "612d6870e7e14fb528576a249ad68e2b1735bd70"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "5fbb4282403046d52a4672765c6761a809bf9f33e699b17e6eb7a93ab7770cc3"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-aarch64-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c6f80106acf58aae77a1ac282ecea93fa68970d"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "9fcdd10e5855ea8c7af75d5b709f7125e06b0dd653e14235503d5ef885a7350d"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-arm-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c291334d394dd7e10dd01a7c6668d6b0d9c53bc3"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "fe4b4ad389108c8b90ae77ed66b62073468a77892483bc11d2be570b64b866db"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-armv7-unknown-linux-gnueabihf.tar.gz"
[[RustToolChain]]
arch = "powerpc64le"
git-tree-sha1 = "3e934caf08591c04285acff2eec61416ff70f7c3"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "c20df5c7133492efc4a5e66f9a41aef3dcb50d2a0d8acef98e635ab1c3e49fdb"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-powerpc64le-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "riscv64"
git-tree-sha1 = "b99f8b27b9421a95319e8c07888f5fc26dd9906a"
lazy = true
libc = "glibc"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "64757537fada45bb7c203ec0d77fda72a11f5d24cf9dcab84cc4168256858a0c"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-riscv64gc-unknown-linux-gnu.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "4b579e3a1b241341c07bdf546f724503215efbd1"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "b2cf07e41d4747ddf3b20962ca9de2a08da00646f55ab4c1b51cef99895bae0a"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-x86_64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "aarch64"
git-tree-sha1 = "5de3b12c62138d109d121bceb6d2246d3081c667"
lazy = true
libc = "musl"
os = "linux"

    [[RustToolChain.download]]
    sha256 = "c26e37bb6f20e49498c552e53e3f34871ba2f7610c7f8b2cce38a48e3570c7de"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-aarch64-unknown-linux-musl.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "0aaa6ce9754a642519f0523c58b21ee1bc2d817f"
lazy = true
os = "freebsd"

    [[RustToolChain.download]]
    sha256 = "c8d2765c9a3a599c8e475ac8b5b448ac9e2d64a891b6014ce5c07dbfc23ce36c"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-x86_64-unknown-freebsd.tar.gz"
[[RustToolChain]]
arch = "i686"
git-tree-sha1 = "980d2e847d6e24a785c7341207ef2486806dc1dc"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "7d287e10e5bf0d54063b3946c51065a7946e122cdbf88e2f2116733605113916"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-i686-pc-windows-msvc.tar.gz"
[[RustToolChain]]
arch = "x86_64"
git-tree-sha1 = "7cc999af4604d7726364b0e554663e183e89fc84"
lazy = true
os = "windows"

    [[RustToolChain.download]]
    sha256 = "f7a1b07636c34c07a684954ebfdf13e6cc12ae825e0f0a385b0d33ac1d05f092"
    url = "https://static.rust-lang.org/dist/rust-1.98.0-x86_64-pc-windows-msvc.tar.gz"
